[package]
name = "hello-world-backend"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.17"
ic-stable-structures = "0.6.7"
ic-wasi-polyfill = {version = "0.7.0", features= ["report_wasi_calls"]}
